import sys
sys.path.append("..")
from src.Utils import timeit

# (venv) (base) ming.li@sjcminglimx0-nb dat % wc -l bioconcepts2pubtator_offsets
#  356922799 bioconcepts2pubtator_offsets

@timeit
def readin_split_by_docID(filepath, output_dir):
    prev_head = None
    abtract_filename = output_dir + "abstract.txt"
    counter = 0
    total_line = 0
    file_counter = 0
    file = open(filepath, "r")
    write_abstract = open(abtract_filename, "w+")
    for each_line in file:
        total_line += 1
        counter += 1
        head = each_line[:15].split("\t")[0].split("|")[0]

        if head != prev_head or head == "":
            # reset the counter as we go into another paper section
            counter = 0
            prev_head = head

        if head == prev_head and counter == 1:
            '''
            based on the file structure, for each pmid
            first line (counter = 0) paper title
            second line (counter = 1) paper abstract
            third line - xxx line (counter > 1) keywords generated by AI
            '''
            write_abstract.writelines(each_line)
            file_counter += 1
        if total_line >= 10000:
            # for debug only, if parsed all, will take ~4 hours
            break
    print(total_line, file_counter)
    file.close()
    write_abstract.close()
    return

if __name__ == '__main__':
    readin_split_by_docID(filepath="../dat/bioconcepts2pubtator_offsets",
                          output_dir="../output/pubtator_parsed/")

